### ISSUE TITLE
implement also a reboot ?

### ISSUE THREAD

**Issue by RaNd250** [Kajkac/ZTE-MC801A-Home-assistant#9]
Could you check if you can merge with this `https://github.com/paddy-314/zteRouterReboot/tree/1e3977979ae2dfb6bb05dc28fb9cda233174f437`
and implement a reboot function and/or a watchdog maybe  ?

**Comment by Kajkac** [comment]
you have rebot defined in switches so you can use that

https://github.com/Kajkac/ZTE-MC801A-Home-assistant/blob/master/switch/switches.yaml
